### ISSUE TITLE
エラー調査

### ISSUE THREAD

**Issue by KimuraYu45z** [lcnem/proximax-pegzone#28]
Shin Neng Wongさんは起動に困っているそうです
次回稼働時、調査をお願いいたします！

```
panic: Error initializing DB: resource temporarily unavailable

goroutine 1 [running]:
github.com/tendermint/tm-db.NewDB(0x11c344b, 0xa, 0x11c2171, 0x9, 0xc00003a870, 0x2b, 0xc0001567b8, 0x40b1cc)
        /home/ubuntu/go/pkg/mod/github.com/tendermint/tm-db@v0.4.0/db.go:72 +0x277
github.com/tendermint/tendermint/lite/proxy.NewVerifier(0x7ffdd8398710, 0x7, 0xc00003a870, 0x2b, 0x7f62d2a46e40, 0xc00016b230, 0x14d31c0, 0x1dbcb20, 0xa, 0x3, ...)
        /home/ubuntu/go/pkg/mod/github.com/tendermint/tendermint@v0.33.0/lite/proxy/verifier.go:24 +0x2dd
github.com/cosmos/cosmos-sdk/client/context.CreateVerifier(0x0, 0x0, 0x0, 0x14ef1c0, 0xc00016b230, 0x7ffdd8398710, 0x7, 0x0, 0x0, 0x14b31c0, ...)
        /home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.1/client/context/verifier.go:52 +0x1c1
github.com/cosmos/cosmos-sdk/client/context.NewCLIContextWithInputAndFrom(0x14b31c0, 0xc0000b6000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.1/client/context/context.go:98 +0x64c
github.com/cosmos/cosmos-sdk/client/context.NewCLIContextWithFrom(...)
        /home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.1/client/context/context.go:114
github.com/cosmos/cosmos-sdk/client/context.NewCLIContext(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/ubuntu/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.38.1/client/context/context.go:119 +0xcb
github.com/lcnem/proximax-pegzone/cmd/pxbrelayer/relayer.LoadTendermintCLIContext(0xc000aafb20, 0xc000e8b780, 0x14, 0x20, 0xc000e8e110, 0x9, 0x7ffdd8398634, 0x16, 0x7ffdd8398710, 0x7, ...)
        /home/ubuntu/proximax-pegzone/cmd/pxbrelayer/relayer/loader.go:18 +0x59
github.com/lcnem/proximax-pegzone/cmd/pxbrelayer/relayer.InitProximaXRelayer(0x14b0bc0, 0xc000ddb020, 0xc000aafb20, 0x14d3200, 0xc000de79a0, 0x7ffdd8398634, 0x16, 0x7ffdd8398710, 0x7, 0x7ffdd8398679, ...)
        /home/ubuntu/proximax-pegzone/cmd/pxbrelayer/relayer/proximax.go:39 +0x161
main.RunProximaxRelayerCmd(0xc0000c7600, 0xc000ddaea0, 0x5, 0x6, 0x0, 0x0)
        /home/ubuntu/proximax-pegzone/cmd/pxbrelayer/main.go:142 +0x4b2
github.com/spf13/cobra.(*Command).execute(0xc0000c7600, 0xc000ddad80, 0x6, 0x6, 0xc0000c7600, 0xc000ddad80)
        /home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:840 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0x1d81e40, 0xb74480, 0x1d81e40, 0x11bc453)
        /home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:945 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
        /home/ubuntu/go/pkg/mod/github.com/spf13/cobra@v0.0.6/command.go:885
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0x1d81e40, 0x13453c8, 0x3, 0xc000def1a0)
        /home/ubuntu/go/pkg/mod/github.com/tendermint/tendermint@v0.33.0/libs/cli/setup.go:89 +0x3c
main.init.0()
        /home/ubuntu/proximax-pegzone/cmd/pxbrelayer/main.go:66 +0x63b
```

**Comment by Kourin1996** [comment]
自分の環境でエラーを再現できてはいませんが、Peggyで立てられていた以下のIssueとおそらく同じのものかと思います
https://github.com/cosmos/peggy/issues/109

PeggyでのPR https://github.com/cosmos/peggy/pull/163 を参考に Relayerのプロセスを一つにまとめるPRを作成しました https://github.com/lcnem/proximax-pegzone/pull/30
